### ISSUE TITLE
Am I missing something?

### ISSUE THREAD

**Issue by todrobbins** [simbolo/cabal-ui#1]
Hi @simbolo, I clone the repo and followed the installation steps but only end up with this screen:

<img width="580" alt="screen shot 2018-09-13 at 5 39 33 pm" src="https://user-images.githubusercontent.com/158590/45521945-8a118880-b77d-11e8-93ed-d9b5a02ad215.png">

I am missing something or is this the only piece of the UI in the repo? Also, nothing happens when I click ok.

Thanks in advance!

**Comment by simbolo** [comment]
@todrobbins Yeah, I am sorry: This is just a bare bones html/css playground. I haven't commited anything else other than the initial design and I think Nikolai implemented everything on Cabal's Desktop main repo.

Quickly after finishing this I drafted some concepts (the ones you saw on the other thread) but I haven't implemented them.

If you want to fiddle with this repo just remove all the .dialog divs to see it working.

**Comment by todrobbins** [comment]
Got it. Thanks!
